var DataAccess = require("../src/data-access")
describe('#DataAccess', function() {
	describe('Create', function() {
		it('rejects request with empty objects (all fields undefined)')
		it('rejects invalid parameter forms')
		it('creates new object')
		it('creates tags')
		it('ignores the id field')
	})
	describe('Sync', function() {
		it('rejects if id is not set')
		it('throws error if it does not exist in the database')
		it('fills object with fields')
	})
	describe('Update', function() {
		it('rejects when all params undefined')
		it('ignores updating no-change parameters')
		it('throws error if id is not set, -1, or invalid')
		it('updates object')
		it('updates tags')
	})
	describe('Search', function() {
		it('rejects empty search object')
		it('logs invalid fields in search object')
		it('rejects no valid fields in search object')
		it('searches partials appropriately')
		it('searches exacts appropriately')
		it('supports multiple-field search')
		it('refines search using all fields (filtering locally)')
		it('rejects invalid search object form')
	})
	describe('List', function() {
		it('max list 100')
		it('returns array of objects')
		it('ascending functions as intended')
	})
	describe('Page', function() {
		it('skips proper amount')
		it('returns expected quantity')
		it('throws error if id is not set, -1, or invalid')
		it('tags are attached')
	})
	describe('Tag', function() {
		it('ignores already-existing tags')
		it('adds tag')
		it('throws error if id is not set, -1, or invalid')
		it('updates object')
	})
	describe('Untag', function() {
		it('ignores non-existent tags')
		it('removes tags')
		it('throws error if id is not set, -1, or invalid')
		it('updates object')
	})
	describe('GetTags', function() {
		it('adds tags array')
		it('throws error if the class does not support tagging')
		it('throws error if id is not set, -1, or invalid')
	})
	describe('Delete', function() {
		it('deletes object')
		it('ignores invalid, -1, or undefined id')
	})
})
